services:
  ros2_rox2026:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: rox2026_container
    ports:
      - "6080:6080" # noVNC (Used on macOS/Windows, ignored on Linux host mode)
    init: true
    stdin_open: true
    tty: true
    privileged: true # Dangerous, but necessary for convenient hardware access.
    network_mode: host
    ipc: host

    environment:
      ROS_DOMAIN_ID: "0"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      FASTRTPS_DEFAULT_PROFILES_FILE: /root/lazytatzv_ws/main_ws/src/bringup/robot_bringup/config/fastdds_config.xml
      DEBIAN_FRONTEND: noninteractive
      # GUI Support
      # If host DISPLAY is set (Linux), use it. Otherwise default to :1 (noVNC).
      DISPLAY: ${DISPLAY:-:1}
      QT_X11_NO_MITSHM: "1"
      # NVIDIA GPU Support (Linux Only)
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    # [MAC/NON-NVIDIA USERS] Comment out the 'deploy' section below if you get GPU errors.
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    volumes:
      - .:/root/lazytatzv_ws
      - ./.ccache:/root/.ccache:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw

    devices:
      - /dev:/dev
      - /dev/dri:/dev/dri # GPU acceleration for Intel/AMD

    shm_size: '2gb' # Increase shared memory for Foxglove/RViz
    working_dir: /root/lazytatzv_ws
    command: bash