services:
  ros2_rox2026:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazy_container
    init: true
    stdin_open: true
    tty: true
    privileged: true # Dangerous, but necessary for convenient hardware access.
    network_mode: host
    ipc: host

    environment:
      ROS_DOMAIN_ID: "0"
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      FASTRTPS_DEFAULT_PROFILES_FILE: /root/lazytatzv_ws/src/bringup/robot_bringup/config/fastdds_config.xml
      DEBIAN_FRONTEND: noninteractive
      # GUI Support
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"

    sysctls:
      - net.core.rmem_max=2147483647
      - net.core.rmem_default=2147483647

    volumes:
      - .:/root/lazytatzv_ws
      - ./.ccache:/root/.ccache:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw

    devices:
      - /dev:/dev
      - /dev/dri:/dev/dri # GPU acceleration for Intel/AMD

    shm_size: '2gb' # Increase shared memory for Foxglove/RViz
    working_dir: /root/lazytatzv_ws
    command: bash