<?xml version="1.0"?>
<package format="3">
  <name>imu_stabilizer</name>
  <version>1.0.0</version>
  <description>Professional Heading Stabilization using IMU + PID</description>
  <maintainer email="tatsv@example.com">tatsv</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>control_toolbox</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
