# Configuration for DDSM115 Motors
# This file is used by speed_dispatcher and individual motor nodes.

/serial_driver:
  ros__parameters:
    device_name: "/dev/ttyUSB1"
    baud_rate: 115200
    flow_control: "none"
    parity: "none"
    stop_bits: "1"

/motors/front_left:
  ros__parameters:
    motor_id: 1
    joint_name: "front_left_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/front_right:
  ros__parameters:
    motor_id: 2
    joint_name: "front_right_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/rear_left:
  ros__parameters:
    motor_id: 3
    joint_name: "rear_left_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/rear_right:
  ros__parameters:
    motor_id: 4
    joint_name: "rear_right_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"
