# ROX2026 Structured Actuator Settings (Robstride AT)

# Robstride公式基盤を使った制御をする際のドライバ等の設定

# Communication Layer
/communication/serial_gateway:
  ros__parameters:
    serial_port: "/dev/ttyUSB1" # udevで管理
    baud_rate: 921600 # 公式datasheetより固定. 触らない

# Hardware Abstraction Layer (HAL)

# max_speed_limit_percentage (0-100)
# モーターの最大速度を制限する為のparameter
/hal/speed_dispatcher:
  ros__parameters:
    front_left_topic: "/motors/front_left/velocity_command"
    front_right_topic: "/motors/front_right/velocity_command"
    rear_left_topic: "/motors/rear_left/velocity_command"
    rear_right_topic: "/motors/rear_right/velocity_command"

# Low-Level Motor Drivers
/motors/front_left:
  ros__parameters:
    motor_id: 0x0C
    joint_name: "front_left_wheel_joint"
    invert_direction: false
    max_speed_limit_percentage: 50.0
    topic_tx_queue: "/communication/tx_queue"
    topic_rx_queue: "/communication/rx_queue"

/motors/front_right:
  ros__parameters:
    motor_id: 0x14
    joint_name: "front_right_wheel_joint"
    invert_direction: true
    max_speed_limit_percentage: 50.0
    topic_tx_queue: "/communication/tx_queue"
    topic_rx_queue: "/communication/rx_queue"

/motors/rear_left:
  ros__parameters:
    motor_id: 0x1C
    joint_name: "rear_left_wheel_joint"
    invert_direction: false
    max_speed_limit_percentage: 50.0
    topic_tx_queue: "/communication/tx_queue"
    topic_rx_queue: "/communication/rx_queue"

/motors/rear_right:
  ros__parameters:
    motor_id: 0x24
    joint_name: "rear_right_wheel_joint"
    invert_direction: true
    max_speed_limit_percentage: 50.0
    topic_tx_queue: "/communication/tx_queue"
    topic_rx_queue: "/communication/rx_queue"
