# Configuration for Robstride EL05 Motors
# This file is used by speed_dispatcher and individual motor nodes.

/serial_driver:
  ros__parameters:
    device_name: "/dev/ttyUSB1"
    baud_rate: 921600
    flow_control: "none"
    parity: "none"
    stop_bits: "1"

/motors/front_left:
  ros__parameters:
    motor_id: 0x0C
    joint_name: "front_left_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/front_right:
  ros__parameters:
    motor_id: 0x14
    joint_name: "front_right_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/rear_left:
  ros__parameters:
    motor_id: 0x1C
    joint_name: "rear_left_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"

/motors/rear_right:
  ros__parameters:
    motor_id: 0x24
    joint_name: "rear_right_wheel_joint"
    topic_tx_queue: "/serial_write"
    topic_rx_queue: "/serial_read"
