# twist_mux configuration for ROX2026
twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      teleop:
        topic: "cmd_vel_joy"
        timeout: 0.5
        priority: 100
      navigation:
        topic: "cmd_vel_nav"
        timeout: 0.5
        priority: 10
      external:
        topic: "cmd_vel_ext"
        timeout: 0.5
        priority: 5
      # Baseline signal to ensure robot stops when no one is talking
      idle:
        topic: "cmd_vel_idle"
        timeout: 1.0
        priority: 1

    locks:
      e_stop:
        topic: "stop_lock"
        timeout: 0.0
        priority: 255
