el05_motor_node:
  ros__parameters:
    motor_id: 0x7f
    host_id: 0xfd
    joint_name: el05_joint
    auto_enable: false
    can_tx_topic: /ssuca/transmit
    can_rx_topic: /ssuca/receive
    feedback_topic: ~/status
    joint_state_topic: /joint_states
    position_min_rad: -12.57
    position_max_rad: 12.57
    velocity_min_rad_s: -50.0
    velocity_max_rad_s: 50.0
    torque_min_nm: -6.0
    torque_max_nm: 6.0
    kp_min: 0.0
    kp_max: 500.0
    kd_min: 0.0
    kd_max: 5.0
