<?xml version="1.0"?>
<package format="3">
  <name>seeed_usb_can_analyzer_driver</name>
  <version>0.1.0</version>
  <description>ROS 2 driver for the Seeed Studio USB-CAN Analyzer</description>
  <maintainer email="maintainer@example.com">maintainer</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>boost</build_depend>
  <build_depend>libatomic</build_depend>
  <build_export_depend>boost</build_export_depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rclcpp_components</depend>
  <depend>lifecycle_msgs</depend>
  <depend>custom_interfaces</depend>
  <exec_depend>boost</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>libatomic</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
